let $configdir='c:\git\config'
let $workdir='c:\work'
let $devdir='c:/git'
let $devdir0='c:/git'
let $devdir1='c:/git'
let $devdir2='c:/git'
let $VIMLOCATION='c:\Vim\vim82'
source $configdir\win.vimrc
set lines=110
